### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by unixorn** [robin-mbg/switch-git#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license.

Please add a license - if you don't have one in mind,  I recommend [choosealicense.com](https://choosealicense.com) to help choose one.

**Comment by robin-mbg** [comment]
Thanks @unixorn, sorry to see this so late. I just added the MIT license. The plugin remains actively used and maintained, it would be awesome to be added to that plugin list.
